### ISSUE TITLE
Doesn't run on literate haskell

### ISSUE THREAD

**Issue by ChristopherKing42** [AtomLinter/linter-hlint#18]

**Comment by Arcanemagus** [comment]
If you run the `Editor: Log Scopes at Cursor` command from the command palette what do you get?

**Comment by ChristopherKing42** [comment]
When I do latex style:

```
Scopes at Cursor

- text.tex.latex.haskell
```

When I do bird style:

```
Scopes at Cursor

- text.tex.latex.haskell
- meta.embedded.haskell
```

**Comment by Arcanemagus** [comment]
I'm not sure what latex/bird style means, but this linter claims to only be able to understand `source.haskell` (Haskell source files).

From the scopes you are listing it looks like you are trying to get it to run on Haskell embedded inside of a LaTeX document, correct?

**Comment by ChristopherKing42** [comment]
@Arcanemagus That is correct. A haskell compiler recognizes a LaTex document as a valid haskell program if it ends with the "*.lhs" extension.

Here is the wiki article https://wiki.haskell.org/Literate_programming
The official specification https://www.haskell.org/onlinereport/haskell2010/haskellch10.html#x17-17900010.4

**Comment by Arcanemagus** [comment]
@ChristopherKing42 this plugin has nothing to do with a Haskell compiler though... as stated in the readme this is simply an interface for [HLint](https://github.com/ndmitchell/hlint). Does `hlint` itself support running on those files? If so it should be a simple matter of just expanding the allowed scopes to include the ones you listed above.

**Comment by ChristopherKing42** [comment]
Yep, `hlint` works on literate haskell.

**Comment by Arcanemagus** [comment]
@mdgriffith as it looks like you are the maintainer for this package do you want to put this together, or do you want me to?

**Comment by ChristopherKing42** [comment]
I'm not the maintainer, this is just a random package I use.

**Comment by Arcanemagus** [comment]
I know, hence why I tagged @mdgriffith :wink:.

**Comment by mdgriffith** [comment]
Hey, thanks guys.  I'll check out the PR and see if it handles the lhs files.
