### ISSUE TITLE
gutter marks does not appear

### ISSUE THREAD

**Issue by ALEXMORF** [AtomLinter/linter-hlint#20]
When using hlint, the error message does show up at the bottom, but the gutter mark does not appear. This is not a problem with base linter, because when I use other linters, such as javac-linter, the gutter mark shows up correctly next to the error.

**Comment by Arcanemagus** [comment]
What is the column for the the errors that have no gutter marker?

**Comment by ALEXMORF** [comment]
Gutter marker simply does not appear no matter which column the error is at.

**Comment by Arcanemagus** [comment]
Can you post a screenshot of the errors you are seeing in the panel? Since the message type comes directly from the linter instead of using a standard one it may be that the messages simply have no known style (and thus no associated gutter style).

**Comment by ALEXMORF** [comment]
![capture](https://cloud.githubusercontent.com/assets/16845654/13228597/b922a3b4-d951-11e5-82f8-1a916bf3851f.PNG)

here is a screenshot of it. Thanks for helping me out.

**Comment by steelbrain** [comment]
@Arcanemagus and I have found [`this line`](https://github.com/AtomLinter/linter-hlint/blob/9cc8f5c5cc712b89234a2b187441106e6d635d76/lib/init.coffee#L44) to be the culprit, basically we're providing relative instead of absolute paths to linter

**Comment by Arcanemagus** [comment]
Interesting, the error message isn't showing in the File tab like it's supposed to. It looks like the paths being returned by the linter are relative to where it was ran, instead of the full path to the file. @mdgriffith do you want to throw together a patch that ignores the path the linter is returning and just returns `filePath` every time?
