### ISSUE TITLE
Add Provider name for Linter v2

### ISSUE THREAD

**Issue by Valdsonjr** [AtomLinter/linter-hlint#24]
As said in [linter-hdevtools](https://github.com/ranjitjhala/linter-hdevtools/issues/13). Not a big deal, but it would be nice to know which Errors/Warnings are given by hdevtools and which ones are given by hlint.

![provider2](https://cloud.githubusercontent.com/assets/6580116/23951694/b523d114-096d-11e7-8dd2-63d686d43a47.png)

**Comment by Arcanemagus** [comment]
Released in v1.0.1 🎉
