### ISSUE TITLE
Cannot stat hlint

### ISSUE THREAD

**Issue by aztecrex** [AtomLinter/linter-hlint#3]
This happens whenever I open atom or save an .hs file.  Using Haskell LTS 2.2. Bootstrap ghc 7.8.4, cabal-init, and happy from hvr ppa.  OS is Ubuntu 14.10 .

Verified hlint is on the path:
```
greg@toroid:~$ which hlint
/home/greg/.cabal/bin/hlint
```

[**Atom Version**: 0.190.0
**System**: linux 3.16.0-34-generic
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat 'hlint'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat 'hlint'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterHLint.Linter._cachedStatSync (/home/greg/.atom/packages/linter/lib/linter.coffee:69:17)
  at LinterHLint.Linter.getCmdAndArgs (/home/greg/.atom/packages/linter/lib/linter.coffee:86:16)
  at LinterHLint.Linter.lintFile (/home/greg/.atom/packages/linter/lib/linter.coffee:127:24)
  at /home/greg/.atom/packages/linter/lib/linter-view.coffee:158:18
  at Array.forEach (native)
  at /home/greg/.atom/packages/linter/lib/linter-view.coffee:157:18
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
```

### Config

```json
{
  "linter": {}
}
```

### Installed Packages

```coffee
# User
ide-haskell, v0.3.6
language-haskell, v1.0.0
linter, v0.12.0
linter-hlint, v0.3.1

# Dev
No dev packages
```

**Comment by mdgriffith** [comment]
Try adding the hlint path explicitly in the package settings.  There may be some issue with picking it up from PATH.

**Comment by legrostdg** [comment]
https://github.com/AtomLinter/Linter/issues/507

**Comment by legrostdg** [comment]
Can't hlint be found automatically from $PATH?

**Comment by mdgriffith** [comment]
I'm not actually sure why not, but it seems like there is some sort of issue with the $PATH lookup.  The default command is "hlint", which should just search for the hlint executable that's on $PATH.
