### ISSUE TITLE
Incompatibility with >=hlint-2.0

### ISSUE THREAD

**Issue by leonschoorl** [AtomLinter/linter-hlint#30]
linter-hlint seems to be incompatible the with current hlint (2.0.8).

With the default settings it crashes with:
```
[Linter] Error running HLint Error: hlint: user error (Failed to find requested hint files:
  Default
  Dollar
  Generalise
)
```
It seems that the values accepted by the `--hint` option changed with hlint-2.0.

(As a workaround I discovered that you can put a empty file (like /dev/null) in the "List of hints to use" field on the linter-hlint config page.)

**Comment by Arcanemagus** [comment]
@leonschoorl This was discovered over in https://github.com/AtomLinter/linter-hlint/pull/26#issuecomment-294548744, unfortunately @mdgriffith never responded and I don't know `hlint` well enough to figure out valid specs for v2. If you could figure out a PR to get this working again that would be great!

**Comment by leonschoorl** [comment]
Would you care much about compatibility with both v1 and v2?
Or would having it work with v2 only be ok?

**Comment by Arcanemagus** [comment]
I don't know the ecosystem around HLint to say whether it would be necessary to support v1. Since linting is generally for ensuring code is accurate and you generally want the latest linter to do so I would say being compatible with v2 is fine as long as it is noted in the readme.

**Comment by mkoloberdin** [comment]
Some info on changes in v.2.0: https://neilmitchell.blogspot.com/2017/04/hlint-20-with-yaml-configuration.html
