### ISSUE TITLE
Linter not activating

### ISSUE THREAD

**Issue by lachy-xe** [AtomLinter/linter-hlint#4]
I have linter-hlint v0.3.1 and linter v0.12.1 installed on Windows 8.1. I have hlint installed and the path configured properly in hlint's settings. If I change the path in the settings to anything different I get an error when opening a haskell file, but when it's set to the correct path nothing will show up in atom, even if there are warnings and errors when I run `hlint .` at the command line.

I know there isn't an issue with the linter plugin, because linter-rubocop works perfectly. I'd appreciate any help getting this to work!

**Comment by mdgriffith** [comment]
Hi!
So, I just did a quick check and the hlint plugin still works on my machine, however I'm using OSX at the moment.  What version of Atom are you on?

**Comment by lachy-xe** [comment]
Okay, my atom version is v0.194.0, which as far as I'm aware is the current latest version.
Thanks! :smile:

**Comment by mdgriffith** [comment]
I think I found the issue.  Try updating linter-hlint to 0.3.2 and let me know how it goes.

**Comment by lachy-xe** [comment]
Working properly now. :smiley:
Thanks for the speedy help!
