### ISSUE TITLE
Only matching one error at a time

### ISSUE THREAD

**Issue by lachy-xe** [AtomLinter/linter-hlint#5]
Hey again, sorry to be a bother haha.
The linter now is only matching the first error from the output of hlint, and all of the subsequent messages are attached to the end of the first one. Once the first error is fixed and the file is re-linted the next one will show up, and so on.
I think somehow the regexp would need to be modified to recognise where each message ends, but my knowledge of regexps isn't strong enough to know how to do that.
Thanks :smile:

**Comment by mdgriffith** [comment]
No problem.  Honestly, it's good to have some feedback from someone on windows.

I think the issue is with windows newlines (\r\n) vs unix(\n).  There's a split statement to break out the different messages.  I've updated the split to work with windows....I think.  Would you mind updating to 0.3.3?

**Comment by lachy-xe** [comment]
Working perfectly, thank you again! :smile_cat:
